include:
  - project: nosana-ci/tools/cicd/gitlab-ci
    file: templates/semver.yml
  - project: nosana-ci/tools/cicd/gitlab-ci
    file: templates/cacheflush.yml

variables:
  NODE_VERSION: 19
  OUTPUT_DIR: .output/public
  PURGE_FILE: purge.json

.npm:
  image: node:$NODE_VERSION
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules
        - .npm
    - key: cache-nuxt-$CI_COMMIT_SHA
      paths:
        - .nuxt

build:
  extends: .npm
  stage: build
  script: yarn install --cache .npm --prefer-offline
  rules:
    - if: $CI_MERGE_REQUEST_ID                                          # merge requests
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH                       # main
    - if: $DEPLOYMENT_BRANCH && $CI_COMMIT_BRANCH == $DEPLOYMENT_BRANCH # optional deployment branch